import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface ExportableResult {
  detectedErrorType: string;
  rootCauseSummary: string;
  suggestedFix: string;
  businessImpact: string;
  fileName?: string | null;
}

function extractPreventiveRec(suggestedFix: string): string {
  const sentences = suggestedFix.split(/\.\s+|\n\n/);
  if (sentences.length > 1) {
    return sentences[sentences.length - 1].trim() || sentences[sentences.length - 2].trim();
  }
  return "Implement monitoring and alerting for this error pattern.";
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function ExportButton({ result }: { result: ExportableResult }) {
  const exportCSV = () => {
    const headers = ["Error Type", "Root Cause", "Suggested Fix", "Preventive Recommendation", "Business Impact"];
    const values = [
      result.detectedErrorType,
      `"${result.rootCauseSummary.replace(/"/g, '""')}"`,
      `"${result.suggestedFix.replace(/"/g, '""')}"`,
      `"${extractPreventiveRec(result.suggestedFix).replace(/"/g, '""')}"`,
      `"${result.businessImpact.replace(/"/g, '""')}"`,
    ];
    const csv = headers.join(",") + "\n" + values.join(",");
    downloadFile(csv, `rootsight-analysis-${Date.now()}.csv`, "text/csv");
  };

  const exportText = () => {
    const text = `
═══════════════════════════════════════════
  RootSight AI — Analysis Report
═══════════════════════════════════════════

📁 File: ${result.fileName || "Pasted log"}
🏷️  Error Type: ${result.detectedErrorType}
📅 Date: ${new Date().toLocaleDateString()}

───────────────────────────────────────────
🔍 ROOT CAUSE EXPLANATION
───────────────────────────────────────────
${result.rootCauseSummary}

───────────────────────────────────────────
🔧 SUGGESTED FIX
───────────────────────────────────────────
${result.suggestedFix}

───────────────────────────────────────────
🛡️ PREVENTIVE RECOMMENDATION
───────────────────────────────────────────
${extractPreventiveRec(result.suggestedFix)}

───────────────────────────────────────────
📊 BUSINESS IMPACT
───────────────────────────────────────────
${result.businessImpact}

═══════════════════════════════════════════
  Generated by RootSight AI
═══════════════════════════════════════════
`.trim();
    downloadFile(text, `rootsight-analysis-${Date.now()}.txt`, "text/plain");
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="h-4 w-4" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportCSV}>Download as CSV</DropdownMenuItem>
        <DropdownMenuItem onClick={exportText}>Download as Text Report</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
